### ISSUE TITLE
Perde - Sahne Oluşturulması

### ISSUE THREAD

**Issue by erdemalkim** [19bal/gad#4]
- Sahnenin oluşturulması ile ilgili gerekli araştırmaların yapılması, 
- Toplanan bilgilerden yola çıkılarak alınacak listesinin oluşturulması,
- Sahnenin oluşturulması.

**Comment by erdemalkim** [comment]
Bu haftaiçi uzeme giderek bilgi toplamaya çalışacağım

**Comment by seyyah** [comment]
ilgili [kitabın](http://www.mediafire.com/?0krn25mznxm) chapter 5 indeki eleman listesi ve fiyat listesini çıkartalım

**Comment by seyyah** [comment]
Build A Mobile Blue/Green Screen

http://www.tubetape.net/servlet/the-15/Green-Screen-and-Support/Detail
